// File generated by FlutterFire CLI.
// Project: jongkuch-85af3

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuGJ_q20obj9xA6hvA89PbLyWoThb_42E',
    appId: '1:733169948632:web:fffc078df42c52435844ad',
    messagingSenderId: '733169948632',
    projectId: 'jongkuch-85af3',
    authDomain: 'jongkuch-85af3.firebaseapp.com',
    storageBucket: 'jongkuch-85af3.firebasestorage.app',
    measurementId: 'G-LXWC6DZNH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6IofWTS9A_LavuAttDZM7a-8K9BlRPnA',
    appId: '1:733169948632:android:b8f0f95a2c2b55e65844ad',
    messagingSenderId: '733169948632',
    projectId: 'jongkuch-85af3',
    storageBucket: 'jongkuch-85af3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVtpwTWtXg8htNG7SmvdsaITP80Pd2YGg',
    appId: '1:733169948632:ios:0778341c82e1263b5844ad',
    messagingSenderId: '733169948632',
    projectId: 'jongkuch-85af3',
    storageBucket: 'jongkuch-85af3.firebasestorage.app',
    iosBundleId: 'com.example.kigaliServicesDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVtpwTWtXg8htNG7SmvdsaITP80Pd2YGg',
    appId: '1:733169948632:ios:0778341c82e1263b5844ad',
    messagingSenderId: '733169948632',
    projectId: 'jongkuch-85af3',
    storageBucket: 'jongkuch-85af3.firebasestorage.app',
    iosBundleId: 'com.example.kigaliServicesDirectory',
  );
}
